travis:
  secure:
    BINSTAR_TOKEN: vKoXddEkfymoUrYnKX3dfPiJQj4lcCFN1RQw8PxdE8Z0Ru1GDOZA6WmQFagEEkEBiB5DLiAqbgmg+d0sxDuL1SZg2q6lwZfkF+DWZWnSh03+zYk5LjAUEpz99Tn/jhCezwqzfzrxWlk3vCVVN129FMfDNoBySTqqCf4IZ3SEUrzNp8Wb+GYn0v7o9b1Ag9ly3h/0VmewaeJZZCdgnGNe1MTTBiXXtcVFEct4nMkaKIMZ8aG8OiVyY83uTJCt7iIEmYpP/OxLGjjXZRUOSONnSxwq8PYZJXNS4xi/m5WH2a0+e0ODjyknewixa38/VyQtK/XWw1SpDqETy23mjIyt6nBPpuuiAskVnfXfrk+h5N1c3UwoFf2QvY1se9gKl0KnOjLGeMpf1b+t6kQ/3Gv9k1iQFrkZtvIWA9Vrk9d8PLVRR+teKNjRjEYjPYzOmiQqeKtv8uzmRaIS3ytRFJvBviWiSFSmp+fJccoSPrdksDvqMjVTbjp4iSyIKkG+4H789DPPB7inMM9iXuUHtalr3LEOsxmeAijCGCoQfkRdoq77HbcFS23C7h4x0z2DoiaTaGqaqTqWa4x2b94Vc/o13ZtfFZCKeXs0XX+2ytL/dxOs6BE4de+QI+oF8wbpXH/v21KFmWH4ZFmU05ru0IzoLHlyJZ681Bh7mf3UwP93dZs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
